name: Generate Code from Swagger using OpenAPI

on:
  push:
    branches:
      - main

jobs:
  generate_code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install OpenAPI Generator
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.3.1/openapi-generator-cli-6.3.1.jar -O openapi-generator-cli.jar
          echo 'java -jar openapi-generator-cli.jar $@' > openapi-generator
          chmod +x openapi-generator
          sudo mv openapi-generator /usr/local/bin/
          
      - name: Generate Code
        run: |
          openapi-generator generate -i openapi-spec.yaml -g spring --additional-properties interfaceOnly=true
          
      - name: Commit and Push Changes
        run: |
          git config --global user.email "stefano.nassi@gmail.com"
          git config --global user.name "nassiesse"
          git add .
          git commit -m "Generated code from Swagger"
          git push
